name: Roz Group
favicon: null
layout_spectrum: 0.8260063943453133
typography_spectrum: 0.6040576081722975
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ce4430'
    - '#151515'
    - '#d3d480'
    - '#52231c'
    - '#ce8d59'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
